on:
  push:

jobs:
  hello:
    runs-on: ubunto-latest
    steps:
      - name : Print Hello world
        run: echo "Hello World" 

goodbye:
  name: My Goodbye job
  needs: hello
  run-on: windows-latest